[server]
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8080

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false


[server]
port = 8501
address = "0.0.0.0"

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "dark"
